### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jrappen** [jrappen/sublime-json#3]
### JSON

- [ ] main
    - [ ] highlight stuff other than array or object at top level as invalid
- [ ] array
    - [ ] trailing commas in array
- [ ] object
    - [ ] leading separators in object
    - [ ] trailing commas in object

### JSON5

- [ ] check whitespace valid chars
- [ ] strings
    - [ ] add multiline with new-line-escapes
    - [ ] add escapes with 2 hex
    - [ ] add escapes for UTF-16, pair with four hex each
    - [ ] no decimal digit after null escpae allowed
    - [ ] add warnings for paragraph separator & line separator
- [ ] object
    - [ ] add ECMAScript identifier

**Comment by jrappen** [comment]
@deathaxe @keith-hall @michaelblyons Any thoughts on adding `meta.sequence.list.item` for items in an array with `meta.sequence.list`? I was looking at sublimehq/Packages#884.

Also, how would I do that here?

<img width="459" alt="image" src="https://user-images.githubusercontent.com/8577450/164300886-71632031-7a2f-4efd-aba7-fa74d15adc7f.png">
